ExamShield/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),  # technical team
    path('', include('mysite.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('administrator/', include('administrator.urls')),
    path('question/', include('question.urls')),
    path('subject/', include('subject.urls')),
    path('assignment/', include('assignment.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'administrator'

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.Register.as_view(), name='register'),
    path('create-faculty/', views.create_faculty, name='create-faculty'),
    path('create-student/', views.create_student, name='create-student'),
    path('edit-institute-profile/', views.edit_institute_profile, name='edit-institute-profile'),
    path('view-student-details/', views.list_students, name='view-student-details'),
    path('view-faculty-details/', views.list_faculties, name='view-faculty-details'),
]

faculty/urls.py
from django.urls import path
from . import views

app_name = 'faculty'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    # TODO: add redirect for '' to login
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('faculty-video-conference/', views.video_conference, name='faculty-video-conference'),
    path('faculty-viva/', views.faculty_viva_view, name='faculty-viva'),

]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.home, name='home'),
]

student/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'student'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    # path('', views.login, redirect('student:login')),
    # TODO: add redirect for '' to login
    path('dashboard/', views.student_dashboard_view, name='dashboard'),
    path('view-result', views.view_result_view, name='view-result'),
    path('check-marks/<int:pk>/', views.check_marks_view, name='check-marks'),
    path('student-marks', views.student_marks_view, name='student-marks'),
    path('start-exam/<int:pk>/', views.start_exam_view, name='start-exam'),
    path('take-exam/<int:pk>/', views.take_exam_view, name='take-exam'),
    path('student-exam', views.student_exam_view, name='student-exam'),
    path('calculate-marks', views.calculate_marks_view, name='calculate-marks'),

    # save result
    path('save-result/<int:course_id>/', views.save_result, name='save-result'),

    # viva
    path('student-viva/', views.student_viva_view, name='student-viva'),
]

student/models.py
from django.contrib.auth.models import User
from django.db import models
from administrator.models import Institute
from subject.models import Subject


class student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institute = models.ForeignKey(Institute, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, null=False, blank=False)
    enroll_no = models.PositiveIntegerField(unique=True, null=False, blank=False)
    subjects = models.ManyToManyField(Subject)

    def __str__(self):
        return f'student-{self.enroll_no}@{self.institute.name}'

student/forms.py
from django import forms

from utils.form_helper import create_attributes
from .models import student as Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['email', 'enroll_no']
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'type': 'email',
                    **create_attributes(
                        placeholder='Email',
                    ),
                }
            ),

            'enroll_no': forms.NumberInput(
                attrs={
                    **create_attributes(
                        placeholder='Enrollment no',
                    ),
                }
            )
        }

student/views.py
from datetime import datetime, timedelta
from random import shuffle

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from mysite.decorators import allowed_users
from question import models as QMODEL
from question.models import Result, Course
from student import models


class Login(View):
    def get(self, request):
        return render(request, 'student/login.html')

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        if username and password:
            user = auth.authenticate(username=username, password=password)
            if user and user.groups.filter(name='student'):
                auth.login(request, user)
                return redirect('student:dashboard')
            else:
                messages.error(request, 'Error: Invalid Credentials!')
                return render(request, 'student/login.html')

        messages.warning(request, 'Please enter credentials to login')
        return render(request, 'student/login.html')


@login_required(login_url='student:login')
def logout(request):
    auth.logout(request)
    return redirect('student:login')


def is_student(user):
    return user.groups.filter(name='STUDENT').exists()


@allowed_users(allowed_groups=['student'])
def student_dashboard_view(request):
    context = {

        'total_course': QMODEL.Course.objects.all().count(),
        'total_question': QMODEL.Question.objects.all().count(),
        'institute': request.user.student.institute.name,
    }
    return render(request, 'student/dashboard.html', context=context)


@allowed_users(allowed_groups=['student'])
def student_marks_view(request):
    courses = QMODEL.Course.objects.all()
    return render(request, 'student/student-marks.html', {'courses': courses})


@allowed_users(allowed_groups=['student'])
def start_exam_view(request, pk):
    course = get_object_or_404(Course, id=pk)

    # can't give exam if exam is over!
    time_left = course.end_time - datetime.now()
    if time_left <= timedelta(microseconds=0):
        messages.info(request, f'Exam for {course.course_name} is over!')
        return redirect('student:student-exam')

    # can't give same exam twice!
    student = request.user.student
    if student.result_set.filter(exam=course):
        messages.info(request, f'You have already given exam for {course.course_name}!')
        return redirect('student:student-exam')

    # for testing purpose only
    # time_left = timedelta(minutes=3)

    # getting time left in req format
    hours, mins, secs = str(time_left).split()[-1].split(':')
    hours = '0' + hours if len(hours) == 1 else hours
    mins = '0' + mins if len(mins) == 1 else mins
    secs = '00'

    questions = QMODEL.Question.objects.filter(course=course)
    total_questions = questions.count()

    # shuffling questions
    questions = list(questions)
    shuffle(questions)

    context = {
        'course': course,
        'questions': questions,
        'total_questions': total_questions,
        'hours': hours,
        'mins': mins,
        'secs': secs,
        'student': request.user.student,
    }
    return render(request, 'student/start-exam.html', context=context)


@allowed_users(allowed_groups=['student'])
def take_exam_view(request, pk):
    course = QMODEL.Course.objects.get(id=pk)
    total_questions = QMODEL.Question.objects.all().filter(course=course).count()
    questions = QMODEL.Question.objects.all().filter(course=course)
    total_marks = 0
    for q in questions:
        total_marks = total_marks + q.marks

    return render(request, 'student/take-exam.html',
                  {'course': course, 'total_questions': total_questions, 'total_marks': total_marks})


@allowed_users(allowed_groups=['student'])
def student_exam_view(request):
    student = request.user.student
    courses = Course.objects.filter(subject__institute=student.institute).order_by('-start_time')
    return render(request, 'student/student-exam.html', {'courses': courses})


@allowed_users(allowed_groups=['student'])
def calculate_marks_view(request):
    if request.COOKIES.get('course_id') is not None:
        course_id = request.COOKIES.get('course_id')
        course = QMODEL.Course.objects.get(id=course_id)

        total_marks = 0
        questions = QMODEL.Question.objects.all().filter(course=course)
        for i in range(len(questions)):

            selected_ans = request.COOKIES.get(str(i + 1))
            actual_answer = questions[i].answer
            if selected_ans == actual_answer:
                total_marks = total_marks + questions[i].marks
        student = models.student.objects.get(user_id=request.user.id)
        result = QMODEL.Result()
        result.marks = total_marks
        result.exam = course
        result.student = student
        result.save()

        return HttpResponseRedirect('view-result')


@allowed_users(allowed_groups=['student'])
def view_result_view(request):
    student = request.user.student
    results = Result.objects.filter(student=student).order_by('-date')
    return render(request, 'student/view-result.html', context={
        'results': results
    })


@allowed_users(allowed_groups=['student'])
def check_marks_view(request, pk):
    course = QMODEL.Course.objects.get(id=pk)
    student = models.student.objects.get(user_id=request.user.id)
    results = QMODEL.Result.objects.all().filter(exam=course).filter(student=student)
    return render(request, 'student/check-marks.html', {'results': results})


@allowed_users(allowed_groups=['student'])
def save_result(request, course_id):
    if request.method != 'POST':
        return HttpResponse('BAD REQUEST')

    student = request.user.student
    marks = request.POST.get('total_score', '')
    course_id = course_id
    submitted_time = request.POST.get('time_submitting', '')

    try:
        course = Course.objects.get(id=course_id)
        Result.objects.create(
            student=student,
            marks=marks,
            exam=course,
            date=submitted_time,
            is_given=True,
        )
        return redirect('student:view-result')
    except Exception as e:
        return HttpResponse('Unable to save result!')


@allowed_users(allowed_groups=['student'])
def student_viva_view(request):
    return render(request, 'student/student-viva.html')

templates/student/check-marks.html
{% extends  'student/general-layout.html' %}

{% block app-main %}
<div class="check-marks">

     <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">View Marks</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Exam Name</th>

          <th>Total Marks</th>
          <th>Attempt</th>
          <th>Exam Date</th>
        </tr>
      </thead>
      {% for t in results %}
      <tr>

        <td> {{t.exam}}</td>
        <td> {{t.marks}}</td>
        <td>Attemp {{ forloop.counter }}</td>
        <td> {{t.date}}</td>


      </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}

templates/student/dashboard.html
{% extends  'student/general-layout.html' %}
{% block title %}ExamShield | Dashboard
{% endblock %}
{% block app-main %}
    <div style="height: 100vh">
        <h1 class="display-5 text-center">Welcome to {{ institute }}</h1>
    </div>
{% endblock %}

templates/student/general-layout.html
{% extends  'base.html' %}
{% block style %}
    {% include 'student/css/main_css.html' %}
{% endblock %}
{% block main %}

    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
    <div class="app-header header-shadow" style="background-color: #D8CEF6;">
        <div class="app-header__logo">
            <div class="logo-src">
                <h5 style="color: rgb(73, 66, 66);font-weight: 700;">VIDHYAM</h5>
            </div>
            <div class="header__pane ml-auto">
                <div>
                    <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                            data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="app-header__mobile-menu">
            <div>
                <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                </button>
            </div>
        </div>
        <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
        </div>
        <div class="app-header__content">
            <div class="app-header-left">

            </div>
            <div class="app-header-right">
                <div class="header-btn-lg pr-0">
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left">
                                <div class="btn-group">
                                    <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                       class="p-0 btn">
                                        {{ user.username }}

                                        <i class="fas fa-user ml-2 opacity-8"></i>
                                    </a>
                                    <div tabindex="-1" role="menu" aria-hidden="true"
                                         class="dropdown-menu dropdown-menu-right">
                                        <button type="button" tabindex="0" class="dropdown-item">
                                            {{ user.username }}
                                        </button>
                                        <div tabindex="-1" class="dropdown-divider"></div>
                                        <a href="{% url 'student:logout' %}" class="dropdown-item">LOG OUT</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="app-main">
        <div class="app-sidebar sidebar-shadow" style="background-color: #D8CEF6;">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                    <span>
                        <button type="button"
                                class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
            </div>
            <div class="scrollbar-sidebar">
                <div class="app-sidebar__inner">
                    <ul class="vertical-nav-menu">
                        <li class="app-sidebar__heading"><a
                                href="{% url 'student:dashboard' %}">Dashboards</a></li>

                        {#                        TODO: do activity tab#}
                        {#                        <li class="app-sidebar__heading">MANAGE ACTIVITY</li>#}
                        {#                        <li>#}
                        {#                            <a href="#">#}
                        {#                                <span><i class="fas fa-eye"></i></span>&nbsp;#}
                        {#                                <span> Activity </span>#}
                        {#                            </a>#}
                        {#                        </li>#}

                        <li class="app-sidebar__heading">MANAGE EXAMINATIONS</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-diagnoses"></i></span>&nbsp;
                                <span> Examinations </span>

                            </a>
                            <ul>
                                <li>
                                    <a href="{% url 'student:student-viva' %}">
                                        <i class="metismenu-icon"></i>
                                        Viva
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'student:student-exam' %}">
                                        <i class="metismenu-icon"></i>
                                        Exams
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'student:view-result' %}">
                                        <i class="metismenu-icon">
                                        </i>Results
                                    </a>
                                </li>

                            </ul>
                        </li>

                        <li class="app-sidebar__heading">MANAGE ASSIGNMENTS</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-book-open"></i></span>&nbsp;
                                <span> Assignments </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="{% url 'assignment:student-view-assignments' %}">
                                        <i class="metismenu-icon">
                                        </i>View Assignments
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'assignment:student-view-all-returned-assignment-instances' %}">
                                        <i class="metismenu-icon">
                                        </i>Return Assignments
                                    </a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                    </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-main__outer">
            <div class="app-main__inner">
                {% block app-main %}{% endblock %}
            </div>
        </div>


    </div>

{% endblock %}

{% block scripts %}
    {% include 'student/js/main_js.html' %}
{% endblock %}

templates/student/login.html
{% extends  'base.html' %}

{% block title %}ExamShield | Student Login{% endblock %}
{% block style %}

    {% include 'mysite/css/main.html' %}
    <style>
        body {
            background-color: #F3EBF6;
            font-family: 'Ubuntu', sans-serif;
        }

        .main {
            background-color: #FFFFFF;
            width: 400px;
            margin: 7em auto;
            border-radius: 1.5em;
            box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
        }

        .sign {
            padding-top: 40px;
            color: #8C55AA;
            font-family: 'Ubuntu', sans-serif;
            font-weight: bold;
            font-size: 23px;
        }

        .un {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
        }

        form.form1 {
            padding-top: 40px;
        }

        .pass {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
        }


        .un:focus, .pass:focus {
            border: 2px solid rgba(0, 0, 0, 0.18) !important;

        }

        .submit {
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: linear-gradient(to right, #9900CC, #9999CC);
            border: 0;

            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 10px;
            padding-top: 10px;
            font-family: 'Ubuntu', sans-serif;
            margin-left: 35%;
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }

        .forgot {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #8C55AA;
            padding-top: 15px;
        }

        a {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #cd4ee4;
            text-decoration: none
        }

        @media (max-width: 600px) {
            .main {
                border-radius: 0px;
            }
        }
    </style>
{% endblock %}
{% block main %}
    {# TODO: Complete Login Page #}

    <nav id="navbar">
        <ul>
            <li class="item"><a href="{% url 'mysite:home' %}">Home</a></li>
            <li class="item"><a href="{% url 'administrator:login' %}">Admin</a></li>
            <li class="item"><a href="{% url 'faculty:login' %}">Faculty</a></li>
            <li class="item"><a href="#">Student</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">About Us</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">Contact Us</a></li>

        </ul>
    </nav>

    <div class="main">
        <div>
            <p class="sign" align="center">Student Login</p>
            <form class="form1" action="{% url 'student:login' %}" method="post">
                {% csrf_token %}
                {% include 'messages.html' %}
                <input class="un " type="text" align="center" placeholder="Username" name="username">
                <input class="pass" type="password" align="center" placeholder="Password" name="password">
                <button class="submit" align="center" type="submit">Sign in</button>
            </form>
            <div class="mt-4" style="margin-left: 32%; padding-bottom: 30px">
                <div class="form-group">
                    <div class="input-group">
                        <a href="" data-bs-toggle="modal" data-bs-target="#forgotpassword">Forgot password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for forgot password -->
    <div class="modal fade" id="forgotpassword" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-primary" id="exampleModalLabel">Change Password</h5>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">&times;</button>
                </div>
                <form id="form4">
                    <div class="modal-body">
                        <div class="form-group mb-3" id="rm_email">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/1177/1177568.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="email" id="femail" class="form-control" name="femail"
                                       placeholder="Email Id." required>
                            </div>
                        </div>
                        <div class="form-group mb-3" id="rm_pass">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/3064/3064211.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="password" id="fpass" class="form-control" name="fpass"
                                       placeholder="Password" required>
                            </div>
                        </div>
                        <div class="form-group" id="rm_cpass">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/3064/3064211.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="password" id="fcpass" class="form-control" name="fcpass"
                                       placeholder="Confirm Password" required>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center" id="rm_update_btn">
                        <div class="modal-footer">
                            <button id="forgotbtn" type="submit" class="btn btn-primary"><i
                                    class="fa fa-spinner fa-spin d-none forgot-spinner" aria-hidden="true"></i> Update
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <footer>
        <div class="center">
            Created by Team Prastigh
        </div>
    </footer>
{% endblock %}
</html>

templates/student/student-exam.html
{% extends  'student/general-layout.html' %}

{% block app-main %}
    <div class="student-exam">

        <div class="panel panel-primary">
            {% include 'messages.html' %}

            <div class="panel-heading">
                <h6 class="panel-title">Courses</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>

                    <th>Exam Name</th>
                    <th>Subject</th>
                    <th>Start Time</th>
                    <th>End Time</th>

                    <th>Status</th>
                </tr>
                </thead>
                {% for course in courses %}
                    <tr>

                        <td> {{ course.course_name }}</td>
                        <td> {{ course.subject.name }}</td>
                        <td> {{ course.start_time }}</td>
                        <td> {{ course.end_time }}</td>

                        <td>
                            {% if course.status == 'Ongoing' %}
                                <a href="{% url 'student:start-exam' course.id %}" class="text-success">On Going</a>
                            {% elif course.status == 'Upcoming' %}
                                <a href="#" class="text-info">Upcoming</a>
                            {% else %}
                                <a href="#" class="text-danger">Finished</a>
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

templates/student/student-marks.html
{% extends  'student/general-layout.html' %}

{% block app-main %}
<div class="student-marks">
<div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">View Marks</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Exam Name</th>

          <th>View Marks</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>

        <td><a class="btn btn-danger btn-xs" href="{% url 'student:check-marks' t.id  %}"><span class="glyphicon glyphicon-eye-open"></span></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}

templates/student/student_dashboard.html
{% extends  'student/general-layout.html' %}
{% block title %}ExamShield | Dashboard
{% endblock %}
{% block app-main %}

{%endblock%}