ExamShield/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),  # technical team
    path('', include('mysite.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('administrator/', include('administrator.urls')),
    path('question/', include('question.urls')),
    path('subject/', include('subject.urls')),
    path('assignment/', include('assignment.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'administrator'

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.Register.as_view(), name='register'),
    path('create-faculty/', views.create_faculty, name='create-faculty'),
    path('create-student/', views.create_student, name='create-student'),
    path('edit-institute-profile/', views.edit_institute_profile, name='edit-institute-profile'),
    path('view-student-details/', views.list_students, name='view-student-details'),
    path('view-faculty-details/', views.list_faculties, name='view-faculty-details'),
]

assignment/urls.py
from django.urls import path
from . import views, api

app_name = 'assignment'

urlpatterns = [
    # faculty operations
    path('create-assignment/', views.create_assignment, name='create-assignment'),
    path('review-assignment/', views.review_assignment, name='review-assignment'),
    path('evaluate-assignment/<int:pk>/', views.evaluate_assignment, name='evaluate-assignment'),
    # student operations
    path('submit-assignment/', views.submit_assignment_instance, name='submit-assignment'),
    path('view-assignments/', views.student_view_all_given_assignments, name='view-assignment'),
    path('view-assignments/<int:assignment_instance_no>/', views.view_assignment_instance,
         name='view-assignment-detail'),

    # api urls
    path('api/get-all-assignments/student:<int:student_enroll_no>/', api.get_all_assignments,
         name='get-all-assignments'),
    path('api/get-all-assignments/student:<int:student_enroll_no>/subject:<int:subject_id>/',
         api.get_all_assignments,
         name='get-all-assignments'),
]

faculty/urls.py
from django.urls import path
from . import views

app_name = 'faculty'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    # TODO: add redirect for '' to login
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('faculty-video-conference/', views.video_conference, name='faculty-video-conference'),
    path('faculty-viva/', views.faculty_viva_view, name='faculty-viva'),

]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.home, name='home'),
]

question/urls.py
from django.urls import path

"""Faculty URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from . import views, api

app_name = 'question'

urlpatterns = [
    # exam urls
    path('faculty-exam/', views.faculty_exam_view, name='faculty-exam'),
    path('question/faculty-add-exam/', views.faculty_add_exam_view, name='faculty-add-exam'),
    path('faculty-view-exam/', views.faculty_view_exam_view, name='faculty-view-exam'),
    path('delete-exam/<int:pk>/', views.delete_exam_view, name='faculty-delete-exam'),
    path('faculty-see-all-student-results/<int:course_id>/', views.faculty_see_all_student_results,
         name='faculty-see-all-student-results'),

    # question urls
    path('faculty-question/', views.faculty_question_view, name='faculty-question'),
    path('faculty-add-question/', views.faculty_add_question_view, name='faculty-add-question'),
    path('faculty-view-question/', views.faculty_view_question_view, name='faculty-view-question'),
    path('see-question/<int:pk>/', views.see_question_view, name='see-question'),
    path('remove-question/<int:pk>/', views.remove_question_view, name='remove-question'),

    # api urls
    path('api/get-course/<int:course_id>/', api.get_course, name='get-course'),
    path('api/get-all-questions/<int:course_id>/', api.get_all_questions, name='get-all-questions'),
]

subject/urls.py
from django.urls import path
from . import views

app_name = 'subject'

urlpatterns = [
    path('add-subject/', views.add_subject, name='add-subject'),
    path('all-subjects/', views.all_subjects, name='all-subjects'),
]

faculty/models.py
from django.contrib.auth.models import User
from django.db import models
from administrator.models import Institute


# Create your models here.
class faculty(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    institute = models.ForeignKey(Institute, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, null=False, blank=False)
    enroll_no = models.PositiveIntegerField(unique=True, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'faculties'

    def __str__(self):
        return f'faculty-{self.enroll_no}@{self.institute}-{self.email}'

faculty/forms.py
from django import forms

from utils.form_helper import create_attributes
from .models import faculty as Faculty


class FacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty
        fields = ['email', 'enroll_no']
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'type': 'email',
                    **create_attributes(
                        placeholder='Email',
                    ),
                }
            ),

            'enroll_no': forms.NumberInput(
                attrs={
                    **create_attributes(
                        placeholder='Enrollment no',
                    ),
                }
            )
        }

faculty/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect
from django.views import View

from mysite.decorators import allowed_users
from question import models as QMODEL
from question.models import Course
from student import models as SMODEL
from django import forms as QFORM

# Create your views here.
from question.views import is_faculty


class Login(View):
    def get(self, request):
        return render(request, 'faculty/login.html')

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        if username and password:
            user = auth.authenticate(username=username, password=password)
            if user and user.groups.filter(name='faculty'):
                auth.login(request, user)
                return redirect('faculty:dashboard')
            else:
                messages.error(request, 'Error: Invalid Credentials!')
                return render(request, 'faculty/login.html')

        messages.warning(request, 'Please enter credentials to login')
        return render(request, 'faculty/login.html')


@login_required(login_url='faculty:login')
def logout(request):
    auth.logout(request)
    return redirect('faculty:login')


@allowed_users(allowed_groups=['faculty'])
def dashboard(request):
    faculty = request.user
    return render(request, 'faculty/dashboard.html', {
        'faculty': faculty,
        'institute': request.user.faculty.institute.name,
    })


@allowed_users(allowed_groups=['faculty'])
def video_conference(request):
    faculty = request.user.faculty
    courses = Course.objects.filter(subject__faculty=faculty).order_by('-start_time')
    context = {
        'courses': courses,
    }
    return render(request, 'faculty/faculty-video-conference.html', context=context)


@allowed_users(allowed_groups=['faculty'])
def faculty_viva_view(request):
    return render(request, 'faculty/faculty-viva.html')

templates/faculty/add-subject.html
{% extends  'faculty/general-layout.html' %}
{% block title %}ExamShield | Add Subject
{% endblock %}
{% block app-main %}
<div class="main-add-stu">
    <p class="sign" align="center">Add Subject</p>
    <form class="form1" method="POST" >
          {% csrf_token %}
        <input  type="number" align="center" name="code" id="code" placeholder="Code">
        <input  type="text" align="center" name="name" id="name" placeholder="Name">
        <button id="done" align="center" name="done" class="done" >Done</button>
    </form>
</div>
{% endblock %}

templates/faculty/all-subjects.html
{% extends  'faculty/general-layout.html' %}
{% block title %}ExamShield | All Subject
{% endblock %}
{% block app-main %}
    <div class="all-subject">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h6 class="panel-title">All Subjects</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>

                    <th>Subject Code</th>
                    <th>Subject Name</th>


                </tr>
                </thead>
                {% for subject in subjects %}
                    <tr>

                        <td> {{ subject.code }}</td>
                        <td> {{ subject.name }}</td>


                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

templates/faculty/dashboard.html
{% extends  'faculty/general-layout.html' %}
{% block title %}ExamShield | Dashboard
{% endblock %}
{% block app-main %}
    <div style="height: 100vh">
        <h1 class="display-5 text-center">Welcome to {{ institute }}</h1>
    </div>
{% endblock %}

templates/faculty/faculty-video-conference.html
{% extends  'faculty/general-layout.html' %}
{% load static %}
{% block title %}ExamShield | Generate Room
{% endblock %}
{% block app-main %}

    <script>
        let ROOM_ID;
        if (localStorage.getItem('exam_id') === 'undefined') {
            ROOM_ID = undefined;
        } else {
            ROOM_ID = localStorage.getItem('exam_id');
        }

        function onGenerateRoom() {
            localStorage.setItem('exam_id', document.getElementById('room').value);
            location.reload();
        }

    </script>

    <script defer src="https://unpkg.com/peerjs@1.2.0/dist/peerjs.min.js"></script>
    <script src="{% static '/js/socket.io.js' %}" defer></script>
    <script src="{% static '/js/script.js' %}" defer></script>
    <script src="{% static '/js/main.js' %}" defer></script>

    <div class="faculty-video-conference">
        <div class="row">
            <div class="col-md-8 col-12">
                <p class="sign" align="center">Generate Room</p>
                <select align="center" name="room" id="room" placeholder="Room ID">
                    <option value="Demo">Demo | Testing</option>
                    {% for course in courses %}
                        {% if course.status == 'Upcoming' or course.status == 'Ongoing' %}
                            <option value="{{ course.room_id }}">{{ course.room_id }}
                                | {{ course.course_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                {#        <input type="text" align="center" name="room" id="room" placeholder="Room ID">#}
                <button id="generate" align="center" name="generate" class="generate" onclick="onGenerateRoom()"
                        style="margin-left:190px;">Generate
                </button>
            </div>
            <div class="col-md-4 col-12 col-mt-3 d-flex justify-content-center align-items-center">

                <div id="video-grid" class="card mb-3"
                     style="max-width: 100%;background-color: rgb(207, 158, 240); margin-top: 25px; padding:5px;">
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/faculty/general-layout.html
{% extends  'base.html' %}
{% block style %}
    {% include 'faculty/css/main_css.html' %}
{% endblock %}
{% block main %}

    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow" style="background-color: #D8CEF6;">
            <div class="app-header__logo">
                <div class="logo-src">
                    <h5 style="color: rgb(73, 66, 66);font-weight: 700;">VIDHYAM</h5>
                </div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-left">

                </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                           class="p-0 btn">
                                            {{ user.username }}
                                            <i class="fas fa-user ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true"
                                             class="dropdown-menu dropdown-menu-right">
                                            <button type="button" tabindex="0" class="dropdown-item">
                                                {{ user.username }}
                                            </button>
                                            <div tabindex="-1" class="dropdown-divider"></div>
                                            <a href="{% url 'faculty:logout' %}" class="dropdown-item">LOG OUT</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="app-main">
            <div class="app-sidebar sidebar-shadow" style="background-color: #D8CEF6;">
                <div class="app-header__logo">
                    <div class="logo-src"></div>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                    data-class="closed-sidebar">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                        <button type="button"
                                class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading"><a
                                    href="{% url 'faculty:dashboard' %}">Dashboards</a></li>

                            {#                            <li class="app-sidebar__heading">MANAGE ACTIVITY</li>#}
                            {#                            <li>#}
                            {#                                <a href="#">#}
                            {#                                    <span><i class="fas fa-eye"></i></span>&nbsp;#}
                            {#                                    <span> Activity </span>#}
                            {#                                </a>#}
                            {#                            </li>#}

                            <li class="app-sidebar__heading">MANAGE EXAMINATIONS</li>
                            <li>
                                <a href="#">
                                    <span><i class="fas fa-diagnoses"></i></span>&nbsp;
                                    <span> Examinations </span>

                                </a>
                                <ul>
                                    <li>
                                        <a href="{% url 'faculty:faculty-viva' %}">
                                            Take Viva
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'question:faculty-exam' %}">
                                            <i class="metismenu-icon">
                                            </i>Exam
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{% url 'faculty:faculty-video-conference' %}">
                                            <i class="metismenu-icon">
                                            </i>Generate Room for Exam
                                        </a>
                                    </li>


                                </ul>
                            </li>

                            <li class="app-sidebar__heading">MANAGE ASSIGNMENTS</li>
                            <li>
                                <a href="#">
                                    <span><i class="fas fa-book-open"></i></span>&nbsp;
                                    <span> Assignments </span>
                                </a>
                                <ul>
                                    <li>
                                        <a href="{% url 'assignment:create-assignment' %}">
                                            <i class="metismenu-icon"></i>
                                            Add Assignments
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'assignment:faculty-view-assignments' %}">
                                            <i class="metismenu-icon">
                                            </i>View Assignments
                                        </a>
                                    </li>

                                </ul>
                            </li>

                            <li class="app-sidebar__heading">MANAGE SUBJECTS</li>
                            <li>
                                <a href="#">
                                    <span><i class="fas fa-book"></i></span>&nbsp;
                                    <span>Subject </span>
                                </a>
                                <ul>
                                    <li>
                                        <a href="{% url 'subject:add-subject' %}">
                                            <i class="metismenu-icon"></i>
                                            Add Subjects
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'subject:all-subjects' %}">
                                            <i class="metismenu-icon">
                                            </i>All Subjects
                                        </a>
                                    </li>


                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="app-main__outer">
                <div class="app-main__inner">
                    {% block app-main %}{% endblock %}
                </div>
            </div>


        </div>
    </div>

{% endblock %}

{% block scripts %}
    {% include 'faculty/js/main_js.html' %}
{% endblock %}

templates/faculty/login.html
{% extends  'base.html' %}

{% block title %}ExamShield | Faculty Login{% endblock %}
{% block style %}

    {% include 'mysite/css/main.html' %}
    <style>
        body {
            background-color: #F3EBF6;
            font-family: 'Ubuntu', sans-serif;
        }

        .main {
            background-color: #FFFFFF;
            width: 400px;
            margin: 7em auto;
            border-radius: 1.5em;
            box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
        }

        .sign {
            padding-top: 40px;
            color: #8C55AA;
            font-family: 'Ubuntu', sans-serif;
            font-weight: bold;
            font-size: 23px;
        }

        .un {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
        }

        form.form1 {
            padding-top: 40px;
        }

        .pass {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
        }


        .un:focus, .pass:focus {
            border: 2px solid rgba(0, 0, 0, 0.18) !important;

        }

        .submit {
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: linear-gradient(to right, #9900CC, #9999CC);
            border: 0;

            padding-left: 40px;
            padding-right: 40px;
            padding-bottom: 10px;
            padding-top: 10px;
            font-family: 'Ubuntu', sans-serif;
            margin-left: 35%;
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }

        .forgot {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #8C55AA;
            padding-top: 15px;
        }

        a {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #cd4ee4;
            text-decoration: none
        }

        @media (max-width: 600px) {
            .main {
                border-radius: 0px;
            }
        }
    </style>
{% endblock %}
{% block main %}
    {# TODO: Complete Login Page #}

    <nav id="navbar">
        <ul>
            <li class="item"><a href="{% url 'mysite:home' %}">Home</a></li>
            <li class="item"><a href="{% url 'administrator:login' %}">Admin</a></li>
            <li class="item"><a href="#">Faculty</a></li>
            <li class="item"><a href="{% url 'student:login' %}">Student</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">About Us</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">Contact Us</a></li>
        </ul>
    </nav>

    <div class="main">
        <div>
            <p class="sign" align="center">Faculty Login</p>
            <form class="form1" action="{% url 'faculty:login' %}" method="post">
                {% csrf_token %}
                {% include 'messages.html' %}
                <input class="un " type="text" align="center" placeholder="Username" name="username">
                <input class="pass" type="password" align="center" placeholder="Password" name="password">
                <button class="submit" align="center" type="submit">Sign in</button>
            </form>
            <div class="mt-4" style="margin-left: 32%; padding-bottom: 30px;">
                <div class="form-group">
                    <div class="input-group">
                        <a href="" data-bs-toggle="modal" data-bs-target="#forgotpassword">Forgot password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for forgot password -->
    <div class="modal fade" id="forgotpassword" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-primary" id="exampleModalLabel">Change Password</h5>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">&times;</button>
                </div>
                <form id="form4">
                    <div class="modal-body">
                        <div class="form-group mb-3" id="rm_email">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/1177/1177568.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="email" id="femail" class="form-control" name="femail"
                                       placeholder="Email Id." required>
                            </div>
                        </div>
                        <div class="form-group mb-3" id="rm_pass">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/3064/3064211.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="password" id="fpass" class="form-control" name="fpass"
                                       placeholder="Password" required>
                            </div>
                        </div>
                        <div class="form-group" id="rm_cpass">
                            <div class="input-group">
                                <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span><img src="https://image.flaticon.com/icons/png/128/3064/3064211.png" height="20"
                                           width="20"></span>
                            </span>
                                </div>
                                <input type="password" id="fcpass" class="form-control" name="fcpass"
                                       placeholder="Confirm Password" required>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center" id="rm_update_btn">
                        <div class="modal-footer">
                            <button id="forgotbtn" type="submit" class="btn btn-primary"><i
                                    class="fa fa-spinner fa-spin d-none forgot-spinner" aria-hidden="true"></i> Update
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <footer>
        <div class="center">
            Created by Team Prastigh
        </div>
    </footer>
{% endblock %}