ExamShield/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),  # technical team
    path('', include('mysite.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('administrator/', include('administrator.urls')),
    path('question/', include('question.urls')),
    path('subject/', include('subject.urls')),
    path('assignment/', include('assignment.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.home, name='home'),
]

question/urls.py
from django.urls import path

"""Faculty URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from . import views, api

app_name = 'question'

urlpatterns = [
    # exam urls
    path('faculty-exam/', views.faculty_exam_view, name='faculty-exam'),
    path('question/faculty-add-exam/', views.faculty_add_exam_view, name='faculty-add-exam'),
    path('faculty-view-exam/', views.faculty_view_exam_view, name='faculty-view-exam'),
    path('delete-exam/<int:pk>/', views.delete_exam_view, name='faculty-delete-exam'),
    path('faculty-see-all-student-results/<int:course_id>/', views.faculty_see_all_student_results,
         name='faculty-see-all-student-results'),

    # question urls
    path('faculty-question/', views.faculty_question_view, name='faculty-question'),
    path('faculty-add-question/', views.faculty_add_question_view, name='faculty-add-question'),
    path('faculty-view-question/', views.faculty_view_question_view, name='faculty-view-question'),
    path('see-question/<int:pk>/', views.see_question_view, name='see-question'),
    path('remove-question/<int:pk>/', views.remove_question_view, name='remove-question'),

    # api urls
    path('api/get-course/<int:course_id>/', api.get_course, name='get-course'),
    path('api/get-all-questions/<int:course_id>/', api.get_all_questions, name='get-all-questions'),
]

templates/quiz/add-subject.html
{% extends  'faculty/general-layout.html' %}
{% block title %}ExamShield | Add Subject
{% endblock %}
{% block app-main %}
<div class="main-add-stu">
    <p class="sign" align="center">Add Subject</p>
    <form class="form1">
        <input  type="text" align="center" placeholder="Subject Name">
        <input  type="number" align="center" placeholder="Subject Code">
        <a class="done" align="center">Done</a>
    </form>
</div>
{% endblock %}

templates/quiz/faculty-add-exam.html
{% extends  'faculty/general-layout.html' %}
{% block app-main %}

    <div class="faculty-add-exam">
        <p class="sign" align="center">Add Exam</p>
        <form class="form1" method="POST" action="{% url 'question:faculty-add-exam' %}">
            {% csrf_token %}
            <div class="form-group">

                {{ courseForm }}

            </div>
            <button type="submit"   class="add">ADD</button>
        </form>
    </div>

{% endblock %}

templates/quiz/faculty-add-question.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}

    <div class="faculty-add-question">
        <p class="sign" align="center">Add Question</p>
        <form method="POST" class="form1">

            {% csrf_token %}
            <div class="form-group">
                {{ questionForm.as_p }}
            </div>
            <button type="submit" class="add">ADD</button>
        </form>
    </div>

{% endblock %}

templates/quiz/faculty-exam.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
    <div class="main-add-stu">
        <p class="sign" align="center">Exam</p>
        <div class="add_exam">
            <a class="create_exam" href="{% url 'question:faculty-add-exam' %}" align="center">Add Exam</a>
        </div>
        <div class="view_exam">
            <a class="create_exam" href="{% url 'question:faculty-view-exam' %}" align="center">View Exam</a>
        </div>
        <div class="view_exam">
            <a class="create_exam" href="{% url 'question:faculty-question' %}" align="center">Questions</a>
        </div>
    </div>
{% endblock %}

templates/quiz/faculty-question.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
<div class="main-add-stu">
    <p class="sign" align="center">Questions</p>
    <div class="add_question">
        <a class="create_exam" href="{% url 'question:faculty-add-question' %}" align="center">Add Questions</a>
    </div>
     <div class="view_question">
        <a class="create_exam" href="{% url 'question:faculty-view-question' %}" align="center">View Questions</a>
    </div>
</div>
{% endblock %}

templates/quiz/faculty-see-all-student-results.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
    <div class="view-result">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h6 class="panel-title">View Student Results - {{ course.course_name }} | {{ course.subject.name }}</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>

                    <th>Student Enroll</th>
                    <th>Student Email</th>
                    <th>Marks Scored</th>
                    <th>Date</th>

                </tr>
                </thead>
                {% for result in results %}
                    <tr>

                        <td> {{ result.student.enroll_no }}</td>
                        <td> {{ result.student.email }}</td>
                        <td> {{ result.marks }}/{{ result.exam.total_marks }}</td>
                        <td> {{ result.date }}</td>


                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

templates/quiz/faculty-view-exam.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
    <div class="faculty-view-exam">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h6 class="panel-title">Exams</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>
                    <th>Exam Name</th>
                    <th>Subject</th>
                    <th>Total Question</th>
                    <th>Total Marks</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>View Questions</th>
                    <th>Results</th>
                </tr>
                </thead>
                {% for course in courses %}
                    <tr>
                        <td>{{ course.course_name }}</td>
                        <td>{{ course.subject.name }}</td>
                        <td>{{ course.question_number }}</td>
                        <td>{{ course.total_marks }}</td>
                        <td>{{ course.start_time }}</td>
                        <td>{{ course.end_time }}</td>
                        <td><a class="btn btn-primary btn-xs" href="{% url 'question:see-question' course.id %}"><span
                                class="glyphicon glyphicon-eye-open"></span></a></td>
                        <td><a class="btn btn-primary btn-xs"
                               href="{% url 'question:faculty-see-all-student-results' course.id %}"><span
                                class="glyphicon glyphicon-eye-open"></span></a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

templates/quiz/faculty-view-question.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
    <div class="faculty-view-exam">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h6 class="panel-title">Exams</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>
                    <th>Exam Name</th>
                    <th>Subject</th>
                    <th>Total Question</th>
                    <th>Total Marks</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>View Questions</th>
                </tr>
                </thead>
                {% for course in courses %}
                    <tr>
                        <td>{{ course.course_name }}</td>
                        <td>{{ course.subject.name }}</td>
                        <td>{{ course.question_number }}</td>
                        <td>{{ course.total_marks }}</td>
                        <td>{{ course.start_time }}</td>
                        <td>{{ course.end_time }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{% url 'question:see-question' course.id %}">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}

templates/quiz/faculty_add_course.html
{% extends 'quiz/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        a:link {
        text-decoration: none;
        }

        </style>
    </head>
    <h2 style="text-align:center; color:blue;">ADD COURSE</h2>
    <form method="POST" autocomplete="off" style="margin:100px;margin-top: 0px;">
        {% csrf_token %}
        <div class="form-group">
            <label for="course_name">Course Name</label>
            {% render_field courseForm.course_name class="form-control" placeholder="Java" %}

            <label for="question_number">Total Question</label>
            {% render_field courseForm.question_number class="form-control" placeholder="10" %}

            <label for="total_marks">Total Marks</label>
            {% render_field courseForm.total_marks class="form-control" placeholder="50" %}
        </div>


        <button type="submit" class="btn btn-primary">ADD</button>
    </form>
    <br><br><br>
{% endblock content %}

templates/quiz/faculty_view_course.html
{% extends 'quiz/adminbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Courses</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Course Name</th>
          <th>Total Question</th>
          <th>Total Marks</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        <td>{{t.question_number}}</td>
        <td>{{t.total_marks}}</td>
        
        <td><a class="btn btn-danger btn-xs" href="{% url 'delete-course' t.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/quiz/fcaulty_view_course.html
{% extends 'quiz/adminbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Courses</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr>

          <th>Course Name</th>
          <th>Total Question</th>
          <th>Total Marks</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        <td>{{t.question_number}}</td>
        <td>{{t.total_marks}}</td>
        
        <td><a class="btn btn-danger btn-xs" href="{% url 'delete-course' t.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/quiz/general-layout.html
{% extends  'base.html' %}
{% block style %}
    {% include 'faculty/css/main_css.html' %}

{% endblock %}
{% block main %}
    {# TODO: Complete Create Dashboard Page #}

    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
    <div class="app-header header-shadow" style="background-color: #D8CEF6;">
        <div class="app-header__logo">
            <div class="logo-src">
                <h5 style="color: rgb(73, 66, 66);font-weight: 700;">VIDHYAM</h5>
            </div>
            <div class="header__pane ml-auto">
                <div>
                    <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                            data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="app-header__mobile-menu">
            <div>
                <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                </button>
            </div>
        </div>
        <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
        </div>
        <div class="app-header__content">
            <div class="app-header-left">

            </div>
            <div class="app-header-right">
                <div class="header-btn-lg pr-0">
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left">
                                <div class="btn-group">
                                    <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                       class="p-0 btn">
                                        Faculty: {{ faculty. }}
                                        <i class="fas fa-user ml-2 opacity-8"></i>
                                    </a>
                                    <div tabindex="-1" role="menu" aria-hidden="true"
                                         class="dropdown-menu dropdown-menu-right">
                                        <button type="button" tabindex="0" class="dropdown-item">Faculty
                                            Account
                                        </button>
                                        <div tabindex="-1" class="dropdown-divider"></div>
                                        <a href="query/logoutExe.php" class="dropdown-item">LOG OUT</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="app-main">
        <div class="app-sidebar sidebar-shadow" style="background-color: #D8CEF6;">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                    <span>
                        <button type="button"
                                class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
            </div>
            <div class="scrollbar-sidebar">
                <div class="app-sidebar__inner">
                    <ul class="vertical-nav-menu">
                        <li class="app-sidebar__heading"><a
                                href="#">Dashboards</a></li>

                        <li class="app-sidebar__heading">MANAGE ACTIVITY</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-eye"></i></span>&nbsp;
                                <span> Activity </span>
                            </a>
                        </li>

                        <li class="app-sidebar__heading">MANAGE EXAMINATIONS</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-diagnoses"></i></span>&nbsp;
                                <span> Examinations </span>

                            </a>
                            <ul>
                                <li>
                                    <a href="#">

                                        Take Viva
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'faculty:faculty-exam' %}">
                                        <i class="metismenu-icon">
                                        </i>MCQ Based
                                    </a>
                                </li>

                            </ul>
                        </li>

                        <li class="app-sidebar__heading">MANAGE ASSIGNMENTS</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-book-open"></i></span>&nbsp;
                                <span> Assignments </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="metismenu-icon"></i>
                                        Add Assignments
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="metismenu-icon">
                                        </i>Review Assignments
                                    </a>
                                </li>

                            </ul>
                        </li>

                        <li class="app-sidebar__heading">MANAGE SUBJECTS</li>
                        <li>
                            <a href="#">
                                <span><i class="fas fa-book"></i></span>&nbsp;
                                <span>Subject </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="{% url 'faculty:add-subject' %}">
                                        <i class="metismenu-icon"></i>
                                        Add Subjects
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="metismenu-icon">
                                        </i>All Subjects
                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-main__outer">
            <div class="app-main__inner">
                {% block app-main %}{% endblock %}
            </div>
        </div>


    </div>

{% endblock %}

{% block scripts %}
    {% include 'faculty/js/main_js.html' %}
{% endblock %}

templates/quiz/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<style>
  .jumbotron{
    margin-bottom: 0px;
  }
</style>
<body>
  {% include "quiz/navbar.html" %}
<br>
<section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
  <div class="container text-center">
    <h1 class="display-1 text-info">Let's Quiz</h1>
    <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
    <p class="lead">We organize quizzes on various topics.</p>

    

    <p class="lead">Sign up if you haven't already and get access to millions of quizzes on the topic of your interest.</p>
    <p><strong> Start Your Journey Here:</strong></p>
    <a href="/student/studentsignup" class="btn btn-lg btn-info" style="padding-right: 35px;"><i class="fa fa-user-plus" aria-hidden="true"></i> Sign Up</a>
    
    <br><br><br>
  </div>  
</section>
  {% include "quiz/footer.html" %}


</body>

</html>

templates/quiz/see-question.html
{% extends  'faculty/general-layout.html' %}

{% block app-main %}
    <div class="see-question">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h6 class="panel-title">Questions - {{ course.course_name }} | {{ course.subject.name }}</h6>
            </div>
            <table class="table table-hover" id="dev-table">
                <thead>
                <tr>
                    <th>Question</th>
                    <th>Marks</th>
                </tr>
                </thead>
                {% for c in questions %}
                    <tr>
                        <td>
                            <div>
                                <b>{{ c.question }}</b>
                                <ol start="1">
                                    <li>{{ c.option1 }}</li>
                                    <li>{{ c.option2 }}</li>
                                    <li>{{ c.option3 }}</li>
                                    <li>{{ c.option4 }}</li>
                                </ol>
                                <i>Answer: {{ c.answer }}</i>
                            </div>
                        </td>
                        <td>{{ c.marks }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

{% endblock %}