ExamShield/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),  # technical team
    path('', include('mysite.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('administrator/', include('administrator.urls')),
    path('question/', include('question.urls')),
    path('subject/', include('subject.urls')),
    path('assignment/', include('assignment.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'administrator'

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.Register.as_view(), name='register'),
    path('create-faculty/', views.create_faculty, name='create-faculty'),
    path('create-student/', views.create_student, name='create-student'),
    path('edit-institute-profile/', views.edit_institute_profile, name='edit-institute-profile'),
    path('view-student-details/', views.list_students, name='view-student-details'),
    path('view-faculty-details/', views.list_faculties, name='view-faculty-details'),
]

faculty/urls.py
from django.urls import path
from . import views

app_name = 'faculty'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    # TODO: add redirect for '' to login
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('faculty-video-conference/', views.video_conference, name='faculty-video-conference'),
    path('faculty-viva/', views.faculty_viva_view, name='faculty-viva'),

]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.home, name='home'),
]

administrator/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Institute(models.Model):
    name = models.CharField(max_length=200,
                            null=False,
                            blank=False,
                            help_text='Enter name of institute')
    code = models.IntegerField(null=True, blank=True, help_text='Enter institute code')
    city = models.CharField(max_length=200, help_text='Enter city', null=True, blank=True)
    state = models.CharField(max_length=200, help_text='Enter state', null=True, blank=True)
    country = models.CharField(max_length=200, help_text='Enter country', null=True, blank=True)
    website_url = models.URLField(
        max_length=200,
        help_text='Enter website url',
        null=True,
        blank=True)

    def __str__(self):
        return self.name


class Administrator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institute = models.OneToOneField('Institute', on_delete=models.CASCADE)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f'{self.user}@{self.institute.name}'


class StudentInfo(models.Model):
    user = models.CharField(max_length=200,
                            null=False,
                            blank=False,
                            help_text='Enter ID')
    institute = models.OneToOneField('Institute', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}@{self.institute.name}'


class FacultyInfo(models.Model):
    user = models.CharField(max_length=200,
                            null=False,
                            blank=False,
                            help_text='Enter faculty ID')
    institute = models.OneToOneField('Institute', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}@{self.institute.name}'

administrator/forms.py
from django import forms
from django.contrib.auth.models import User

from utils.form_helper import create_attributes
from .models import (
    Administrator,
    Institute
)


# 'class': 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(
                attrs={
                    **create_attributes(
                        placeholder='Username',
                    ),
                }
            ),

            'password': forms.PasswordInput(
                attrs={
                    **create_attributes(
                        placeholder='Password',
                    ),
                }
            )
        }


class InstituteForm(forms.ModelForm):
    class Meta:
        model = Institute
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(
                attrs={
                    **create_attributes(
                        placeholder='Institute name',
                    ),
                }
            ),

            'code': forms.NumberInput(
                attrs={
                    'min': 1,
                    **create_attributes(
                        placeholder='Institute code',
                    ),
                }
            ),

            'city': forms.TextInput(
                attrs={
                    **create_attributes(
                        placeholder='City',
                    ),
                }
            ),

            'state': forms.TextInput(
                attrs={
                    **create_attributes(
                        placeholder='State',
                    ),
                }
            ),

            'country': forms.TextInput(
                attrs={
                    **create_attributes(
                        placeholder='Country',
                    ),
                }
            ),

            'website_url': forms.URLInput(
                attrs={
                    **create_attributes(
                        placeholder='Website URL',
                    ),
                }
            ),
        }


class AdministratorForm(forms.ModelForm):
    class Meta:
        model = Administrator
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'type': 'email',
                    **create_attributes(
                        placeholder='Email',
                    ),
                }
            )
        }

administrator/views.py
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.db import IntegrityError
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.urls import reverse
from django.views import View
from student.models import student as Student
from faculty.models import faculty as Faculty
from subject.models import Subject
from faculty.forms import FacultyForm
from student.forms import StudentForm
from mysite.decorators import allowed_users
from .models import Administrator, User
from .forms import (
    UserForm,
    InstituteForm,
    AdministratorForm
)
from utils.random_password import generate_random_password


class Register(View):
    def get(self, request):
        context = {
            'user_form': UserForm(),
            'institute_form': InstituteForm(),
            'administrator_form': AdministratorForm()
        }
        return render(request, 'administrator/register.html', context=context)

    def post(self, request):
        user_form = UserForm(data=request.POST)
        institute_form = InstituteForm(data=request.POST)
        administrator_form = AdministratorForm(data=request.POST)

        # all valid data send by request
        if user_form.is_valid() and institute_form.is_valid() and administrator_form.is_valid():
            # saving user
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = True
            user.is_staff = True
            user.save()

            # saving institute
            institute = institute_form.save()

            # saving administrator
            administrator = administrator_form.save(commit=False)
            administrator.user = user
            administrator.institute = institute
            administrator.save()

            # adding to administrator group
            administrator_group = Group.objects.get(name='administrator')
            administrator_group.user_set.add(administrator.user)

            # redirecting to login page
            return HttpResponseRedirect(reverse('administrator:login'))

        # invalid data sent via request
        context = {
            'user_form': user_form,
            'institute_form': institute_form,
            'administrator_form': administrator_form,
        }
        messages.error(request, f'''Errors: 
        {user_form.errors.as_text()}
        {administrator_form.errors.as_text()}
        {institute_form.errors.as_text()}
        ''')
        return render(request, 'administrator/register.html', context=context)


class Login(View):
    def get(self, request):
        return render(request, 'administrator/login.html')

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        if username and password:
            user = auth.authenticate(username=username, password=password)
            if user and user.groups.filter(name='administrator'):
                auth.login(request, user)
                return redirect('administrator:dashboard')
            else:
                messages.error(request, 'Error: Invalid Credentials!')
                return render(request, 'administrator/home.html')

        messages.warning(request, 'Please enter credentials to login')
        return render(request, 'administrator/login.html')


@allowed_users(allowed_groups=['administrator'])
def create_faculty(request):
    password = generate_random_password()

    if request.method == 'GET':
        context = {
            'password': password,
            'faculty_form': FacultyForm(),
        }
        return render(request, 'administrator/create-faculty.html', context=context)

    elif request.method == 'POST':
        # getting data to create faculty
        faculty_password = request.POST.get('password', '')
        faculty_form = FacultyForm(data=request.POST)

        if faculty_form.is_valid() and faculty_password:
            # data is valid
            faculty_username = faculty_form.cleaned_data['email']

            try:
                # creating faculty
                new_user = User.objects.create_user(username=faculty_username, password=faculty_password)
                faculty = faculty_form.save(commit=False)
                faculty.user = new_user
                faculty.institute = request.user.administrator.institute
                faculty.save()

                # adding faculty to faculty group
                faculty_group = Group.objects.get(name='faculty')
                faculty_group.user_set.add(faculty.user)

                messages.success(request, 'Faculty Created Successfully!')

            except IntegrityError as ie:
                # i.e if user exists in database
                messages.error(request,
                               f'Faculty can\'t be created! An user with username {faculty_username} already exists!')

            context = {
                'password': password,
                'faculty_form': FacultyForm(),
            }
            return render(request, 'administrator/create-faculty.html', context=context)

        else:
            # if invalid data passed
            context = {
                'password': password,
                'faculty_form': faculty_form,
            }

            error_message = f'''
            Faculty can't be created because
            {faculty_form.errors.as_text()}
            '''
            messages.error(request, error_message)
            return render(request, 'administrator/create-faculty.html', context=context)

    # tried requesting page using any other methods
    return HttpResponse('BAD REQUEST')


@allowed_users(allowed_groups=['administrator'])
def create_student(request):
    password = generate_random_password()

    if request.method == 'GET':
        context = {
            'password': password,
            'student_form': StudentForm(),
        }
        return render(request, 'administrator/create-student.html', context=context)

    elif request.method == 'POST':
        # getting data to create student
        student_password = request.POST.get('password', '')
        student_form = StudentForm(data=request.POST)

        if student_form.is_valid() and student_password:
            # data is valid
            student_username = student_form.cleaned_data['email']

            try:
                # creating student
                new_user = User.objects.create_user(username=student_username, password=student_password)
                student = student_form.save(commit=False)
                student.user = new_user
                student.institute = request.user.administrator.institute
                student.save()

                # adding student to student group
                student_group = Group.objects.get(name='student')
                student_group.user_set.add(student.user)

                messages.success(request, 'Student Created Successfully!')

            except IntegrityError as ie:
                # i.e if user exists in database
                messages.error(request,
                               f'Student can\'t be created! An user with username {student_username} already exists!')

            context = {
                'password': password,
                'student_form': StudentForm(),
            }
            return render(request, 'administrator/create-student.html', context=context)

        else:
            # if invalid data passed
            context = {
                'password': password,
                'student_form': student_form,
            }

            error_message = f'''
                Student can't be created because
                {student_form.errors.as_text()}
                '''
            messages.error(request, error_message)
            return render(request, 'administrator/create-student.html', context=context)

    # tried requesting page using any other methods
    return HttpResponse('BAD REQUEST')


@allowed_users(allowed_groups=['administrator'])
def edit_institute_profile(request):
    # TODO: update institute profile
    return render(request, 'administrator/edit-institute-profile.html')


@allowed_users(allowed_groups=['administrator'])
def dashboard(request):
    user = request.user
    institute = user.administrator.institute
    context = {
        'user': user,
        'total_faculties': Faculty.objects.filter(institute=institute).count(),
        'total_subjects': Subject.objects.filter(institute=institute).count(),
        'total_students': Student.objects.filter(institute=institute).count(),
        'institute': institute,
    }
    return render(request, 'administrator/dashboard.html', context=context)


@login_required(login_url='administrator:login')
def logout(request):
    auth.logout(request)
    return redirect('administrator:login')


@login_required(login_url='administrator:login')
def list_faculties(request):
    institute = request.user.administrator.institute
    faculties = Faculty.objects.filter(institute=institute)
    return render(request, 'administrator/view-faculty-details.html', context={'faculties': faculties})


@login_required(login_url='administrator:login')
def list_students(request):
    institute = request.user.administrator.institute
    students = Student.objects.filter(institute=institute)
    return render(request, 'administrator/view-student-details.html', context={'students': students})

templates/administrator/create-faculty.html
{% extends  'administrator/general-layout.html' %}
{% block title %}ExamShield | Add Faculty
{% endblock %}
{% block app-main %}
    <div class="main-add-stu">
        <p class="sign" align="center">Add Faculty</p>
        <form class="form1" method="POST" action="{% url 'administrator:create-faculty' %}">
            {% csrf_token %}

            {% include 'messages.html' %}

            {{ faculty_form.email }}
            {{ faculty_form.enroll_no }}

            <input type="text" align="center" placeholder="Password" name="password" value="{{ password }}">
            <button class="share" align="center" type="submit">Share</button>
        </form>
    </div>
{% endblock %}

templates/administrator/create-student.html
{% extends  'administrator/general-layout.html' %}
{% block title %}ExamShield | Create Student
{% endblock %}
{% block app-main %}
    <div class="main-add-stu">
        <p class="sign" align="center">Add Student</p>
        <form class="form1" method="POST" action="{% url 'administrator:create-student' %}">
            {% csrf_token %}

            {% include 'messages.html' %}

            {{ student_form.email }}
            {{ student_form.enroll_no }}

            <input type="text" align="center" placeholder="Password" name="password" value="{{ password }}">
            <button class="share" align="center" type="submit">Share</button>
        </form>
    </div>
{% endblock %}

templates/administrator/edit-institute-profile.html
{% extends  'administrator/general-layout.html' %}
{% block title %}ExamShield | Institute
{% endblock %}

{% block app-main %}
    <div class="main">
        <p class="sign" align="center">Edit Institute</p>
        <form class="form1">
            <input type="text" align="center" placeholder="Username">
            <input type="Text" align="center" placeholder="Address">
            <input type="text" align="center" placeholder="Contact">
            <input type="text" align="center" placeholder="Website">
            <input type="email" align="center" placeholder="Email">
            <input type="number" min="1" align="center" placeholder="Institute code">
            <a class="reset" align="center">Reset</a>
            <a class="done" align="center">Done</a>
        </form>
    </div>
{% endblock %}

templates/administrator/general-layout.html
{% extends  'base.html' %}
{% block style %}
    {% include 'administrator/css/main_css.html' %}

{% endblock %}
{% block main %}

    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow" style="background-color: #D8CEF6;">
            <div class="app-header__logo">
                <div class="logo-src">
                    <h5 style="color: rgb(73, 66, 66);font-weight: 700;">
                        VIDHYAM
                    </h5>
                </div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-left">

                </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                           class="p-0 btn">
                                            {{ user.username }}
                                            <i class="fas fa-user ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true"
                                             class="dropdown-menu dropdown-menu-right">
                                            <button type="button" tabindex="0" class="dropdown-item">Admin Account
                                            </button>
                                            <div tabindex="-1" class="dropdown-divider"></div>
                                            <a href="{% url 'administrator:logout' %}" class="dropdown-item">LOG OUT</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="app-main">
            <div class="app-sidebar sidebar-shadow" style="background-color: #D8CEF6;">
                <div class="app-header__logo">
                    <div class="logo-src"></div>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                    data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                        </button>
                    </div>
                </div>
                <div class="app-header__menu">
                <span>
                    <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading"><a
                                    href="{% url 'administrator:dashboard' %}">Dashboards</a>
                            </li>

                            <li class="app-sidebar__heading">MANAGE FACULTY</li>
                            <li>
                                <a href="#">
                                    <span><i class="fa fa-user"></i></span>&nbsp;
                                    <span> Faculty </span>

                                </a>
                                <ul>
                                    <li>
                                        <a href="{% url 'administrator:create-faculty' %}">

                                            Add Faculty
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'administrator:view-faculty-details' %}">
                                            <i class="metismenu-icon">
                                            </i>View Faculty Details
                                        </a>
                                    </li>

                                </ul>
                            </li>

                            <li class="app-sidebar__heading">MANAGE STUDENTS</li>
                            <li>
                                <a href="#">
                                    <span><i class="fa fa-users"></i></span>&nbsp;
                                    <span> Students </span>
                                </a>
                                <ul>
                                    <li>
                                        <a href="{% url 'administrator:create-student' %}">
                                            <i class="metismenu-icon"></i>
                                            Add Student
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'administrator:view-student-details' %}">
                                            <i class="metismenu-icon">
                                            </i>View Student Details
                                        </a>
                                    </li>

                                </ul>
                            </li>


                            <li class="app-sidebar__heading">Institute Detail</li>
                            <li>
                                <a href="{% url 'administrator:edit-institute-profile' %}">
                                    <span><i class="fa fa-university"></i></span>&nbsp;
                                    <span> Edit Institute Detail </span>
                                </a>
                            </li>


                        </ul>
                    </div>
                </div>
            </div>

            <div class="app-main__outer">
                <div class="app-main__inner">
                    {% block app-main %}{% endblock %}
                </div>
            </div>


        </div>
    </div>
{% endblock %}

{% block scripts %}
    {% include 'administrator/js/main_js.html' %}
{% endblock %}

templates/administrator/register.html
{% extends  'base.html' %}

{% block title %}ExamShield | Register{% endblock %}
{% block style %}

    {% include 'mysite/css/main.html' %}
    <style>
        body {
            background-color: white;
            font-family: 'Ubuntu', sans-serif;
        }

        .main-reg {
            background-color: #FFFFFF;
            width: 400px;
        {#height: 940px;#} margin: 7em auto;
            border-radius: 1.5em;
            box-shadow: 0 11px 35px 2px rgba(0, 0, 0, 0.14);
        }

        .sign {
            padding-top: 40px;
            color: #8C55AA;
            font-family: 'Ubuntu', sans-serif;
            font-weight: bold;
            font-size: 23px;
        }

        form.form1 {
            padding-top: 40px;
        }

        input {
            width: 76%;
            color: rgb(38, 50, 56);
            font-weight: 700;
            font-size: 14px;
            letter-spacing: 1px;
            background: rgba(136, 126, 126, 0.04);
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            outline: none;
            box-sizing: border-box;
            border: 2px solid rgba(0, 0, 0, 0.02);
            margin-bottom: 50px;
            margin-left: 46px;
            text-align: center;
            margin-bottom: 27px;
            font-family: 'Ubuntu', sans-serif;
        }

        .un:focus,
        .pass:focus {
            border: 2px solid rgba(0, 0, 0, 0.18) !important;

        }

        .submit {
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: linear-gradient(to right, #9900CC, #9999CC);
            border: 0;

            padding: 10px 40px;
            font-family: 'Ubuntu', sans-serif;
            margin-left: 35%;
            font-size: 13px;
            box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
        }

        .submit:hover {
            color: black;
        }

        .forgot {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #9e53c7;
            padding-top: 30px;
        }

        a {
            text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
            color: #cf64e2;
            text-decoration: none;
        }

        @media (max-width: 600px) {
            .main {
                border-radius: 0;
            }
        }
    </style>
{% endblock %}
{% block main %}

    <nav id="navbar">
        <ul>
            <li class="item"><a href="{% url 'mysite:home' %}">Home</a></li>
            <li class="item"><a href="{% url 'administrator:login' %}">Admin</a></li>
            <li class="item"><a href="{% url 'faculty:login' %}">Faculty</a></li>
            <li class="item"><a href="{% url 'student:login' %}">Student</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">About Us</a></li>
            <li class="item"><a href="{% url 'mysite:home' %}">Contact Us</a></li>

        </ul>
    </nav>

    <div class="main-reg">
        <p class="sign" align="center">Admin Registration</p>
        <form class="form1" action="{% url 'administrator:register' %}" method="post">
            {% csrf_token %}
            {% include 'messages.html' %}
            {{ user_form.username }}
            {{ user_form.password }}
            {{ administrator_form.email }}
            {{ institute_form.name }}
            {{ institute_form.code }}
            {{ institute_form.city }}
            {{ institute_form.state }}
            {{ institute_form.country }}
            {{ institute_form.website_url }}
            <br>
            <br>

            <button class="submit" type="submit" align="center">Sign up</button>
            <p class="forgot" align="center" style="padding-bottom: 30px"><a href="{% url 'administrator:login' %}">Already
                have an account?</a></p>
        </form>
    </div>

    <footer>
        <div class="center">
            Created by Team Prastigh
        </div>
    </footer>
{% endblock %}